# Build customization
builds:
  - binary: tgf
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ignore:
      # Windows arm64 is not used and does not compile well as of writing
      - goos: windows
        goarch: arm64

# Archive customization
archives:
  - format: zip

    replacements:
      amd64: 64-bits
      darwin: macOS

    files:
      - nothing.*

# GitHub release customization
release:
  draft: true
  prerelease: true
